dpAutoRigSystem/Modules/Library/dpControls.py, dpAutoRigSystem/dpAutoRig.py
Fixed issue about guide unpin. Now we add the parentConstraint in the correct namespace. So we can remove it finding by name.
Need to have a more ellegant way to do, like using message attribute instead, for example.
=> #221 Unpin guide fix

dpAutoRigSystem/Modules/dpLayoutClass.py, dpAutoRigSystem/Modules/dpSingle.py, dpAutoRigSystem/dpAutoRig.py
Just a simple UI fix to enable sdk locator checkbox when realoading Single module layout.
Also changed the sdkLocator value to zero when we create the Single module. This affects and it is automatic applied to create integrated script by Tweaks module.
=> #237 Single enable sdk locator checkbox

dpAutoRigSystem/Modules/dpSingle.py, dpAutoRigSystem/dpAutoRig.py
Fixed #255 in Dev spreadsheet about rotate zero the Single SDK locator group to be aligned to the guide correctelly.
=> #255 ZeroOut Single SDK Locator group

dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
#265 Lock zero autoClavicle follow attribute temporarily while we find a solution to issue related to rotate gound controls and not calculated the offset correctely. Maybe change it to use a simple aimConstraint instead.
=> #265 Lock zero autoClavicle temp

dpAutoRigSystem/dpAutoRig.py
#263 just changed the Eye pupil control to yellow instead of black in order to help Animators to find this control in front of a black pupil shader.
=> #263 Eye yellow pupil control

dpAutoRigSystem/Modules/dpHead.py, dpAutoRigSystem/dpAutoRig.py
#283 fixed Head error when calling setupJawMove method passing *args. Just removed *args to work.
Thanks Caio for the feedback.
Co-Authored-By: caiolubel <7073504+caiolubel@users.noreply.github.com>
=> #283 Fixed Head invertRot variable

dpAutoRigSystem/Modules/dpFinger.py, dpAutoRigSystem/dpAutoRig.py
Fixed #176 finger stretchable.
The issue was about the joints scale compensate attribute.
We added a new attribute in the Main Control to change joint scale compensate attributes.
Now the stretch first null transform position starts at the main control position instead of the first joint zero.
Fixed the ikCtrl orientation too.
=> #176 Finger stretchable

dpAutoRigSystem/Extras/sqCopyPasteShapes.py, dpAutoRigSystem/Modules/Library/dpControls.py, dpAutoRigSystem/dpAutoRig.py
Keep replaced control shape as the first child of the transform.
Then, we'll use keyboard arrows respecting Maya hierarchy structure by default.
=> #154 Replace control shape order

dpAutoRigSystem/Extras/sqCopyPasteShapes.py, dpAutoRigSystem/dpAutoRig.py
Updated sqCopyPasteShape extra module:
#162 - Replace shape and keep visibility connection.
#317 - Fixed Control Shape with same name bug.
#324 - Continue if not found control to replace.
=> #162 replace connected shape

dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
Fixed #344 autoOrient issue for quaduped Limbs. We forced to do a refresh for the parentConstraint offset.
=> #344 Limb quadruped leg extra autoOrient fix

dpAutoRigSystem/Controls/Presets/Default.json, dpAutoRigSystem/Modules/dpHead.py, dpAutoRigSystem/dpAutoRig.py
N143 fixed Head quadruped neck autoRotate.
We changed the channel to be inverted, because quadruped head control has a different rotate order than biped.
=> N143 Head quadruped neck autoRotate fix

dpAutoRigSystem/Modules/dpHead.py, dpAutoRigSystem/dpAutoRig.py
Fixed Head control zeroOut rotate with many neck segments.
We just changed the orientConstraint to a parentConstraint skipping translate.
=> N355 Head zeroOut rotate fix

dpAutoRigSystem/dpAutoRig.py
First Python 3 supported version for Maya 2022 or earlier.
Release candidate.
=> N401 Migrate to Python 3

dpAutoRigSystem/Modules/dpNose.py, dpAutoRigSystem/dpAutoRig.py
Just removed L-R names in the Nostril joint label to fix the mirror skinning weight issue.
=> N372 Fixed Nostril joint label

dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
N432 - Added a new attribute named useOriginalRotation to Limb extrem controller to be able choose activate or not the alignWorld feature.
Thanks Roy for the script.
Co-Authored-By: Roy Nieterau <roy_nieterau@hotmail.com>
=> N432- Limb added UseOriginalRotation attribute

dpAutoRigSystem/Modules/dpWheel.py, dpAutoRigSystem/dpAutoRig.py
Fixed scale constraint from wheel main control to wheel main joint to fix the optionCtrl rigScale issue. Scale Constraint Sufix from "SsC" to "ScC".
=> N442 - Wheel Main Scale Constraint Fix 

dpAutoRigSystem/Modules/dpEye.py, dpAutoRigSystem/dpAutoRig.py
N434 - Added new attribute to Eye specular control in order to follow eye subcontrol rotation.
N352 - Set guide specular off by default.
=> N434 - Eye specular follow attribute

dpAutoRigSystem/Languages/English.json, dpAutoRigSystem/Languages/Francais.json, dpAutoRigSystem/Languages/Portugues.json, dpAutoRigSystem/dpAutoRig.py
Added on dpAutoRig.py a function to check if there're dpGuides imported to the scene and ask if the user wants do delete the namespace. This function is called inside the function jobReloadUI(). When pressing to reload UI, the autoRig will also check for imported guides. When guides were imported, they will be renamed to avoid duplicated customNames.
=> 464 check existing imported guides

dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
Fixed Limb autoClavicle follow issue not orienting the scalable main group. Instead of that we just used the shoulder null group to orient the articulation joint. Shoulder null group was renamed to shoulder ref group, because it's now used to receive the Jax and Jar shoulder joints when we ask to have corrective joints.
=> N545 Fixed Limb autoClavicle follow issue

dpAutoRigSystem/Modules/dpBaseClass.py, dpAutoRigSystem/dpAutoRig.py
Adjusted corrective joints calibration by control radius. Just multiplying the given preset calibration value to the module guide radius before set the calibrate attribute.
=> N544 Jcr calibration by ctrlRadius

dpAutoRigSystem/Extras/dpCorrectionManager.py, dpAutoRigSystem/dpAutoRig.py
Fixed deleting corrupted corrective manager network. Renamed RigScale_MD to DistanceRigScale_MD to be clear this node is used just in distance setup.
=> N535 Delete corrective network

dpAutoRigSystem/Modules/Library/dpUtils.py, dpAutoRigSystem/Modules/dpBaseClass.py, dpAutoRigSystem/Modules/dpChain.py, dpAutoRigSystem/Modules/dpEye.py, dpAutoRigSystem/Modules/dpFinger.py, dpAutoRigSystem/Modules/dpFkLine.py, dpAutoRigSystem/Modules/dpFoot.py, dpAutoRigSystem/Modules/dpHead.py, dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/Modules/dpNose.py, dpAutoRigSystem/Modules/dpSingle.py, dpAutoRigSystem/Modules/dpSpine.py, dpAutoRigSystem/Modules/dpSteering.py, dpAutoRigSystem/Modules/dpSuspension.py, dpAutoRigSystem/Modules/dpWheel.py, dpAutoRigSystem/dpAutoRig.py
Changed the name for data groups for each module to be _Static_Grp and _Scalable_Grp. Also edited the staticGrp to have 2 new message attributes linked to the controlsGrp and scalableGrp.
=> N428 Group naming

dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
Changed the old useOriginalRotate attribute to the alignWorld attritube in order to be more logical name and value. We passed this value by a new reverseNode.
=> N596 - Limb alignWorld attribute

dpAutoRigSystem/Controls/dpBaseControlClass.py, dpAutoRigSystem/Modules/Library/dpControls.py, dpAutoRigSystem/dpAutoRig.py
Showing the controllers rotateOrder attribute as non keyable in the channelBox.
=> N164 Display rotateOrder attribute

dpAutoRigSystem/Modules/Library/jcRibbon.py, dpAutoRigSystem/dpAutoRig.py
Using the replace function to length multiplyDivide to avoid repeated name like _MD1. Also changed bttm to bottom name.
=> N600 - Reviewed stretch naming

dpAutoRigSystem/Extras/Presets/FacialJoints.json, dpAutoRigSystem/Extras/dpFacialControl.py, dpAutoRigSystem/dpAutoRig.py
Implemented sneer and grimace translate Z axis to control the upper and lower lips roll in and out.
Expected these blendShapes target names:
- UpperLipFront
- UpperLipBack
- LowerLipFront
- LowerLipBack
=> N345 sneer grimace z axis

dpAutoRigSystem/Modules/dpFoot.py, dpAutoRigSystem/dpAutoRig.py
Improved the Foot roll non keyable attributes in order to set the footRollAngle and footRollPlant as non keyable and avoid the animation conflicts.
=> N629 Foot roll non keyable attributes

dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
Changed the rotate order of wrist joint correctives to YZX instead of YXZ to avoid the pop when rotating in Z.
=> N626 Limb wrist fixed Jcr rotZ pop

dpAutoRigSystem/Modules/Library/dpControls.py, dpAutoRigSystem/dpAutoRig.py
Reapply deformers when mirroring the control shapes, if they exists.
=> N646 Mirror shape reconnect deformers

dpAutoRigSystem/Validator/CheckOut/dpTargetCleaner.py, dpAutoRigSystem/dpAutoRig.py
Fixed the keepIt renderGrp issue. Now we don't touch tho the Render_Grp and its children.
=> N638 TargetCleaner deleting issue fix

dpAutoRigSystem/Pipeline/dpPackager.py, dpAutoRigSystem/Pipeline/dpPipeliner.py, dpAutoRigSystem/Pipeline/dpPublisher.py, dpAutoRigSystem/dpAutoRig.py
Just removing the existing file with same name to avoid overwrite conflicts when archiving existing published old files.
=> N664 Overwrite archived published old version

dpAutoRigSystem/Extras/dpMatchMesh.py, dpAutoRigSystem/dpAutoRig.py
Conform Maya2024 to use MatchMesh just changing an "underscore" for a "dot" in: om.MGlobal.getActiveSelectionList(meshList)
=> N679 Conform Maya2024 MatchMesh.

dpAutoRigSystem/Pipeline/dpPackager.py, dpAutoRigSystem/dpAutoRig.py
Fixed the Packager imager getting the next empty block in the section zero to add the texts.
=> N692 Packager HUD imager fix

dpAutoRigSystem/Pipeline/dpPackager.py, dpAutoRigSystem/dpAutoRig.py
Fixed image preview fit view issue.
Just rotating Z as zero for the persp camera before generating the rigging image preview.
=> N713 Image preview camera rotateZ zero fix

dpAutoRigSystem/Extras/dpCustomAttr.py, dpAutoRigSystem/dpAutoRig.py
Fixed UI for self.addCustomAttrTFG changing only if we're working with custom attributes. This way we avoid update dpID issues like v4.03.00 release video.
=> N718 Update dpID customAttr UI.

dpAutoRigSystem/dpAutoRig.py
Just limited the min and maximum values of the Limb showControls attribute when it's integrated with Foot module. Thanks Oseias for the feedback.
=> N682 Limit reverseFoot showControls attribute.

dpAutoRigSystem/Validator/CheckOut/dpDisplayLayers.py, dpAutoRigSystem/dpAutoRig.py
Fix display layer validator when there's duplicated name in the scene. Using fullName and fullPath for the functions: listRelatives and editDisplayLayerMembers.
Last commit cleaning print and try/except. Thank you.
=> 736 fix display layer validator

dpAutoRigSystem/Extras/dpCopySkin.py, dpAutoRigSystem/dpAutoRig.py
Changed the CopySkin to accept Maya2024 multiple skinClusters, copy the skinning to existing skinCluster mesh, transfering the method, working with duplicated name and ready to run by code.
=> N318 CopySkin existing method code duplicated multi

dpAutoRigSystem/Modules/dpFkLine.py, dpAutoRigSystem/Modules/dpLayoutClass.py, dpAutoRigSystem/dpAutoRig.py
Just fixed the segment number change to zero error with a set module attribute to zero in the guide base node.
=> N738 FkLine back to zero segment error fixed

dpAutoRigSystem/Validator/CheckOut/dpUnknownNodesCleaner.py, dpAutoRigSystem/dpAutoRig.py
Just fixed an error in the Unknown node cleaner checkout validator to avoid stop working if the node is locked.
=> N750 Delete locked unknown nodes

dpAutoRigSystem/Extras/dpRivet.py, dpAutoRigSystem/dpAutoRig.py
Added conditional on dpRivet FaceToRivet to check Maya's version when using morphDeformer to avoid geometry missplacing. Minimal Maya's version: 2022.3. Thank you for the improvements, Danilo.
=> 773 dprivet morph conditional maya version

dpAutoRigSystem/Validator/CheckOut/dpColorSetCleaner.py, dpAutoRigSystem/dpAutoRig.py
It checks if the colorset node exists before trying to delete it.
=> N771 ColorSet cleanup validator fix

dpAutoRigSystem/Validator/CheckIn/dpGeometryHistory.py, dpAutoRigSystem/dpAutoRig.py
Fixed the Geometry History checkin validator to avoid found issue when the mesh shape has input connections by texture nodes. Added an ignoreNodeTypeList.
=> N784 Geometry history ignore node type list

dpAutoRigSystem/Modules/Library/dpSoftIk.py, dpAutoRigSystem/Modules/dpFoot.py, dpAutoRigSystem/Modules/dpLimb.py, dpAutoRigSystem/dpAutoRig.py
Worked the controllers visibility and stretch disable when in fk mode, for these tasks:
N463 - Hide reverseFoot ctrls if in Fk mode
N721 - Hide Foot_Ball_Ctrl when Limb in FK
N755 - Disable ik stretch when in fk mode
=> N463 reverse foot ctrl display

dpAutoRigSystem/Controls/Presets/Classic.json, dpAutoRigSystem/Controls/Presets/Cubic.json, dpAutoRigSystem/Controls/Presets/Default.json, dpAutoRigSystem/Extras/dpLimbSpaceSwitch.py, dpAutoRigSystem/dpAutoRig.py
Implemented root pivot control setup. The new controller will connect translate to the root_ctrl's rotate pivot. Changed limbSpaceSwitch to use Ctrls_Visiblity_Grp instead Root_Ctrl.
=> N811-root-pivot-control

dpAutoRigSystem/Pipeline/dpPipeliner.py, dpAutoRigSystem/Pipeline/dpPublisher.py, dpAutoRigSystem/dpAutoRig.py
Implemented a feature to read the _dpPipeline/dpCustomAssetName.json file and get the name to save the published file if exists.
=> N813 Custom asset name to publishing files

dpAutoRigSystem/Extras/dpRivet.py, dpAutoRigSystem/dpAutoRig.py
Due to a new update in maya 2023, a new version with two dots in a string must be taken account for.
=> 817 doubledot float conversion

dpAutoRigSystem/Modules/Library/dpIkFkSnap.py, dpAutoRigSystem/dpAutoRig.py
Deactivating ikFkSnap scriptNode if the OptionCtrl ikFkSnap attribute is zero. This is an workround to not have keyframes in the timeline when the ikFkSnap is off.
=> N834 Auto keyframe from ikFkSnap change issue fixed

dpAutoRigSystem/dpAutoRig.py
Correcting error when try to create new guides in old rigs.
=> 826 root pivot ctrl parenting

dpAutoRigSystem/Modules/Library/dpUtils.py, dpAutoRigSystem/Pipeline/Validator/CheckOut/dpProxyCreator.py, dpAutoRigSystem/dpAutoRig.py
Added a new method in the dpUtils to removeFromSets. Call this method when ProxyCreator duplicates the mesh to cleanup it from sets.
=> N828 - Proxy without sets
