- dpAutoRigSystem/Extras/Ui/PoseReader.py
- dpAutoRigSystem/Extras/Ui/SpaceSwitcher.py
- dpAutoRigSystem/Extras/Ui/SpaceSwitcher.ui
- dpAutoRigSystem/Extras/Ui/SpaceSwitcher.ui.OLD
- dpAutoRigSystem/Extras/dpPoseReader.py
- dpAutoRigSystem/Extras/dpSpaceSwitcher.py
- dpAutoRigSystem/Extras/dpUpdateRigInfo.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/libSerialization/__init__.py
- dpAutoRigSystem/dpAutoRig.py
New pull request to fix issue #5. Some sstk call were not in a try catch so outside of squeeze studio environment, it will crash. We also need to find a way to prevent the autorig to crash when an extra tool doesn't load correctly, because the auto-rig would still work correctly.
Also add somw work on the spaceSwitcher to have a tool to manage any type of space switching.
I will accept the pull request to ensure the issue #5 is fixed.
> Fix issue #5

- dpAutoRigSystem/Extras/Ui/SpaceSwitcher.py
- dpAutoRigSystem/Extras/Ui/SpaceSwitcher.ui
- dpAutoRigSystem/Extras/dpSpaceSwitcher.py
- dpAutoRigSystem/dpAutoRig.py
I have merged the latest change done in the original system by Danillo and also include a fix for issue #28 which will prevent the auto-rig to crash when a module doesn't load correctly.
There is also a some work done on the SpaceSwitcher, but it's still not totally done yet.
Thanks Renaud for the fix.
> Merge and Fix module loading

- dpAutoRigSystem/dpAutoRig.py
Clean up dpAutoRig header code and update it.
> Updated Header

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added Limb uniform scale multiplier attributes in Ik and Fk controls.
> 028 uniform scale multiplier

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Created a new feature to Head jaw close.
Reviewed node connections to isolate Y and Z axis.
Implemented the setupJawMove method.
Added upper and lower lip setup for mouth closed.
New attributes to output open and close jaw values into a blendShape node target input attributes.
Need to test in production and set good default values.
> 031 lips super closed

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added Limb scalable length feature.
> 216 limb scalable length

- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpSingle.py
- dpAutoRigSystem/dpAutoRig.py
Added a new locator for Single indirect skinning setup using as setDrivenKeys as support to extra controls.
> #235 Single extra SDK locator

- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpCar.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Fixed #239 Numbering mirror issue.
Edited preview mirror guide custom name to avoid errors duplicanting guides and finding wrong numbering.
> #239 Numbering mirror fix

- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/dpAutoRig.py
#257 Changed HeadDeformer setDrivenKey to remapValue in order to encapsulate that curve in the Graph Editor.
> #257 Changed HeadDeformer SDK to RemapValue

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
#271 Fixed Limb creation without Joint Articulation error.
> #271 Fixed Limb without Jar error

- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/dpAutoRig.py
#279 Fixed Head mirror issue about controls orientation and also inverted shapes.
> #279 Fixed Head mirror

- dpAutoRigSystem/dpAutoRig.py
#225 Trying to fix the issue about autoInstall error loading a missing dictionary key.
> #225 Auto Install remove itself issue fix

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Thanks Caio Hidaka for the help.
> #240 upper head

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Important update to fix Limb autoRotate issue about orientation of middle Ribbons setup.
> #302 leg bend autoRotate fix

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Limb autoClavicle issue about rotating ground controls.
> #148 autoclavicle world matrix

- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/dpAutoRig.py
Fixed #270 Finger minimum segment to 2.
Also fixed an issue in Finger ik about the main control drives the position of the first ik joint.
> #270 Finger min segment

- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Extras/Presets/FacialJoints.json
- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/dpAutoRig.py
Worked on Facial Controls items:
#158 BigSmile target
#267 Facial Controls Z axis
#268 Lips Control target redesign
#269 Face Control new attributes
> #267 Facial Controls Z axis

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
#61 improved Limb poleVector calculation.
Now we are using vectors to find a better place to poleVector position.
Also we locked some guides attributes to avoid user make mistakes.
Thanks Renaud Lessard for the swivel position code we based.
> #061 Limb poleVector calculation

- dpAutoRigSystem/dpAutoRig.py
#236 Added the validateMasterGrp method to check if the All_Grp is a valid masterGrp.
> #236 Avoid existing masterGrp name issue

- dpAutoRigSystem/Modules/dpNose.py
- dpAutoRigSystem/dpAutoRig.py
#328 Fixed  Nose bottom joint label.
> #328 Nose bottom joint label

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Modules/dpSteering.py
- dpAutoRigSystem/dpAutoRig.py
Implemented transfer, import and mirror controls calibration.
Also renamed limb attributes to uniformScaleMultiplier.
> #325 Transfer Calibration

- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Implemented new Head neck segments.
Updated biped (2 segments) and quadruped (3 segments).
Reviewed controls and joints parenting.
Changed neck control shape to cubic circle by default.
> #030 Head neck joints

- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/dpAutoRig.py
N353 Fixed error when trying to reduce Head neck segments number.
> N353 Head reduce neck segments error fix

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added a new feature to Limb module for new additional joints.
Created controls child of extra bend controls.
It'll be useful to tweaks using the skinCluster in the final mesh.
> 377 ribbon add joints

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Changed utils joint articulation function to setup scale by default.
Also started to work with Finger ik/fk scale issue.
Need to further fixes about Finger ik stretch with Limb uniformScale.
> N348 Jar scale update

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Just a first check if the float is calculated correctly when finding the start stretch value in the Limb module.
Still need to check all the code.
> WIP N361 - Float precision

- dpAutoRigSystem/Modules/dpSpine.py
- dpAutoRigSystem/dpAutoRig.py
Enhanced N351 - Spine minimum segments to 3.
> N351 - Spine min segments to 3

- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/dpAutoRig.py
N331 - Fixed Finger thumb cycle about stretch and parenting All_Grp transform node.
Thanks Caio Hidaka for the report.
> N331 thumb cycle

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Back follow attribute to Limb autoClavicle to 0.3 by default.
> N330 - Limb autoClavicle active

- dpAutoRigSystem/dpAutoRig.py
Just updated the dpAutoRig.py file with the syntax ready to Python3 for:
print
backticks
operators <>
from maya import cmds / mel
class (object)
> N392 py2 modernization 00

- dpAutoRigSystem/Extras/dpCopySkin.py
- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/Extras/dpIkFkSnap.py
- dpAutoRigSystem/Extras/dpIsolate.py
- dpAutoRigSystem/Extras/dpMatchMesh.py
- dpAutoRigSystem/Extras/dpPoseReader.py
- dpAutoRigSystem/Extras/dpPrintSelection.py
- dpAutoRigSystem/Extras/dpSelectAllControls.py
- dpAutoRigSystem/Extras/dpTargetMirror.py
- dpAutoRigSystem/Extras/dpUpdateRigInfo.py
- dpAutoRigSystem/Extras/dpZipper.py
- dpAutoRigSystem/Extras/sqSpaceSwitcher.py
- dpAutoRigSystem/Languages/Translator/dpTranslator.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/Library/libSerialization/__init__.py
- dpAutoRigSystem/Modules/Library/libSerialization/pluginMaya.py
- dpAutoRigSystem/Modules/Library/sqIkFkTools.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Scripts/dpArm.py
- dpAutoRigSystem/Scripts/dpBike.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpCar.py
- dpAutoRigSystem/Scripts/dpLeg.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/Scripts/dpTweaks.py
- dpAutoRigSystem/_dpAutoRig_shelfButton.txt
- dpAutoRigSystem/dpAutoRig.py
Worked on Python2 modernization: updated all print statement.
> WIP N392 Py2 print

- dpAutoRigSystem/Extras/dpMatchMesh.py
- dpAutoRigSystem/Extras/dpTargetMirror.py
- dpAutoRigSystem/Scripts/dpArm.py
- dpAutoRigSystem/Scripts/dpBike.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpCar.py
- dpAutoRigSystem/Scripts/dpLeg.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/Scripts/dpTweaks.py
- dpAutoRigSystem/dpAutoRig.py
Replaced all backticks for repr() in the code, excluding expressions.
> WIP N392 Py2 backticks

- dpAutoRigSystem/Extras/dpAddHandFollow.py
- dpAutoRigSystem/Extras/dpColorOverride.py
- dpAutoRigSystem/Extras/dpCopyPasteAttr.py
- dpAutoRigSystem/Extras/dpCopySkin.py
- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/Extras/dpIkFkSnap.py
- dpAutoRigSystem/Extras/dpIsolate.py
- dpAutoRigSystem/Extras/dpMatchMesh.py
- dpAutoRigSystem/Extras/dpPoseReader.py
- dpAutoRigSystem/Extras/dpPrintSelection.py
- dpAutoRigSystem/Extras/dpReorderAttr.py
- dpAutoRigSystem/Extras/dpRivet.py
- dpAutoRigSystem/Extras/dpSelectAllControls.py
- dpAutoRigSystem/Extras/dpTargetMirror.py
- dpAutoRigSystem/Extras/dpUpdateRigInfo.py
- dpAutoRigSystem/Extras/dpZipper.py
- dpAutoRigSystem/Extras/sqCopyPasteShapes.py
- dpAutoRigSystem/Languages/Translator/dpTranslator.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/dpAutoRig.py
Reviewed all root class definition with (object).
> WIP N392 Py2 modernization class (object)

- dpAutoRigSystem/Extras/dpUpdateRigInfo.py
- dpAutoRigSystem/dpAutoRig.py
Detach from PyMEL because Maya2022 need it to be installed as an additional component.
> N405 - No PyMEL for dpUpdateRigInfo

- dpAutoRigSystem/dpAutoRig.py
Removed all PyMEL code for dpAutoRig.py
> N404 no pymel dpar main

- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/Extras/dpZipper.py
- dpAutoRigSystem/Languages/Translator/dpTranslator.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed dpTranslator dictionary data read.
> WIP N401 migrate py3 dpTranslator

- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Modules/dpSingle.py
- dpAutoRigSystem/dpAutoRig.py
WIP N401 - Migrate to Python 3
Removed all older Maya version support before 2022.
> WIP N401 - removed older Maya version support

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Also reviewed compare operators and divisions by // that returns integer instead of float.
> WIP N401 removed filter

- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Reactivated dpUpdater using DPAR_VERSION_PY3 variable.
> WIP N401 Migrate Py3 updater

- dpAutoRigSystem/dpAutoRig.py
Fixed colorOverride conditional to check if it's already set.
> N401 Migrate to Py3 colorOverride fix

- dpAutoRigSystem/Extras/dpCorrectionManager.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/dpAutoRig.py
Added some new attributes and nodes to CorrectionManager be able to set a range of input and output values when extracting angle.
> N453 CorrectionManager range values

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/dpAutoRig.py
Fixed an issue about volume variation of Limb Jar for legs.
Just added a conditional to leg connect in scaleX instead of scaleY (kept for arm).
> N433 - Limb leg jar volume variation

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
N229 - Clavicle and legHips scalable.
N466 - Limb Fk scalable in length.
N467 - Scalable clavicle.
> N466 limb fk scalable

- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/dpAutoRig.py
N439 fixed issue about Maya2022 new deformer concept to use set or componentTag depending of the userPrefs.
> N439 - HeadDeformer set of componentTag fix

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
N026 - Limb poleVector follow review.
N339 - Added new Pin attribute.
N421 - Fixed poleVector constraint interpolation type to shortest.
Changed Limb fk follow to isolate all to Root_Ctrl.
> N026 polevector follow

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpSpine.py
- dpAutoRigSystem/dpAutoRig.py
Added Spine sub controls named Base and Tips.
> N420 spine subcontrols

- dpAutoRigSystem/Modules/Library/dpSoftIk.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Implemented Limb softIk calibration attributes.
> N469 softik calibration

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Corrected _PaC suffix globaly.
> 468-constraint-suffix

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/dpAutoRig.py
> N481 prefix review

- dpAutoRigSystem/dpAutoRig.py
Removed old code line to cancel auto update from v3 to v4.
> N483 AutoUpdate optionVar Fix

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Limb module error when trying to find bendGrps from ribbons in some quadruped types. Now ribbons are allowed for quadrupeds to... need to test in production.
> N473 Fixed Limb bendGrps for quadrupeds

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/dpAutoRig.py
Added new limit to rig scale attribute.
Updated version and description.
> N457-set-minimum-rigscale

- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/dpAutoRig.py
Changed segments position calculation.
Changed auto rotate attribute calculation.
> N354 - Neck autoRotate calculation.

- dpAutoRigSystem/dpAutoRig.py
Fixed issue about using the Add skin influence and Maya 2022 get an error to do not use removeUnusedInfluence flag.
It isn't happen in Maya 2023.
Just removed that flag to avoid this issue.
> N486 add skin influence issue

- dpAutoRigSystem/Languages/Translator/dpTranslator.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/dpAutoRig.py
Just changed sorted(list) to list.sort() in order to avoid issue after 5 elements when creating the guides.
> N487 fixed module instance sort issue

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Scripts/dpArm.py
- dpAutoRigSystem/Scripts/dpLeg.py
- dpAutoRigSystem/dpAutoRig.py
Fixed alignWorld setup and verified the oriention of wrist/ankle controllers.
> N475 Limb extrem rotation

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
N501 - checked all attribute defaultValue to work properly.
Attribute defaultValue Leg/Foot issue fix.
> N501 - Attribute defaultValue reviewed

- dpAutoRigSystem/Extras/dpRivet.py
- dpAutoRigSystem/dpAutoRig.py
> 472-rivet-close

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
> N497 duplicate limb error

- dpAutoRigSystem/dpAutoRig.py
Added model version attribute in the All_Grp.
> Added model version attribute

- dpAutoRigSystem/Extras/dpCorrectionManager.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added a new feature to Limb called corrective where we run the CorrectionManager to create a network and calibrate the setup to output the extracted angle of the corner joint (elbow/knee) as an attribute to use this value to control the blendShape to apply as a deformation fix. We're planning to use this same outputValue from the corrective network to drive the corrective joints we'll implement further.
> N023 - Limb auto corner correction

- dpAutoRigSystem/Languages/Translator/dpTranslator.py
- dpAutoRigSystem/dpAutoRig.py
Fixed the sorted list from a dictionary in the Translator.
> N516 - Translator fix dic sort error

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/dpAutoRig.py
Added neck and head corrective joints as setup of 4 controllers to Head module.
> N539 Head corrective joints

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed corrective joints mirror calibration issue.
> N550 jcr mirror calibration

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/dpAutoRig.py
Added progress window to show a user feedback when importing the controller's calibration.
> N366 - Import calibration progressWindow

- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/dpAutoRig.py
N521 - Fixed Chain module building issue for rotated guides. Just changed when create the ikCtrl parentConstraint to clusterNode and using the ik last control to define the upLocator for the aimConstraint.
> N521 - Fixed Chain building issue

- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/dpAutoRig.py
Implemented corrective joints to Finger module.
This branch is related to the N077 Expand joints. It's the same, so done for these two tasks.
> N538 Finger corrective joints

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/dpAutoRig.py
Reload guide and add or remove pin setup based on the pinGuide attribute value.
> N250 Reload PinGuide

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/dpAutoRig.py
Storing and restoring locked attributes when pinning or unpinning guides.
> N206 pinGuide locked attrs

- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Limb stretch issue for biped legs about footHeel positive rotation.
Co-Authored-By: Caio Hidaka <61671684+caiohidaka@users.noreply.github.com>
> N551 Fixed footHeel positive rotation

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Extras/dpAddHandFollow.py
- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/dpAutoRig.py
Implemented Head sub controller featured.
> N546 Head sub controller

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Changed Option_Ctrl ikFkBlend attributes to have Fk suffix.
> N604 ikFkBlend attribute name

- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Added Breath and Belly to Quadruped spine when it's on Complete mode.
> N549 - Quadruped extra controls

- dpAutoRigSystem/Extras/dpCorrectionManager.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/dpAutoRig.py
Added the feature to chose the interpolation method of the remapValue node when using the CorrectiveManager. There're Linear, Smooth and Spline.
We use Linear as default.
> N530 - Corrective Manager Interpolation

- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/dpAutoRig.py
Changed the stretch locator parent to foot ball control instead of its group.
> N258 - Fixed reverseFoot knee stretch issue

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Changed the Limb poleVector behavior to have a better solution following the ik controller.
> N612 Limb poleVector behavior

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added a new Limb ik wrist/ankle sub controller.
> N027 - Limb ik extrem sub control

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Reviewed naming convention for Limb ik effector.
> N310 - Limb ik effector naming review

- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/dpAutoRig.py
Implemented follow attribute to the upperLip follows the lowerLip in the Head module.
> N343 Head upperLip follow lowerLip

- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpNose.py
- dpAutoRigSystem/dpAutoRig.py
Implemented the Nose space switch to follow upperHeadCtrl or upperJawCtrl. UpperJawCtrl is the value by default.
> N316 Nose space switch

- dpAutoRigSystem/Extras/dpUpdateGuides.py
- dpAutoRigSystem/dpAutoRig.py
Remove unused old namespace from deleted guides.
> 535-del-old-namespaces

- dpAutoRigSystem/dpAutoRig.py
Fixed bug in the autoOrient poleVector setup.
> N616 Limb arm poleVector fix

- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/dpAutoRig.py
Added condition to fix Sneer/Grimace translateY calling lips Front targets issue.
Co-Authored-By: SaulAlm <96533080+SaulAlm@users.noreply.github.com>
> N617 - Lips roll fix

- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/dpAutoRig.py
Lock Finger zero guide rotateZ attribute to avoid wrong angle of joint articulation.
> N631 Lock Finger zero guide rotateZ

- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/dpAutoRig.py
Separated the Facial Controls group in these sub groups, children of these controllers:
HeadSubCtrl (Face)
ChinCtrl (Grimace)
UpperJawCtrl (LipCorner, Sneer, LipsMain)
UpperHeadCtrl (Brows, Eyelids)
> N266 facial ctrls split groups

- dpAutoRigSystem/Pipeline/dpPipeliner.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Pipeliner data dictionary storing the sceneName in the json file.
> N638 Publish reopen current file if error.

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/dpAutoRig.py
Implemented mirror control shapes by using a button in the Control tab UI.
> N065 Mirror control shapes

- dpAutoRigSystem/dpAutoRig.py
Fixed keeping pipeline data files.
Just check if there're json files to keep, otherwise just continue.
> N639 Fixed auto updater issue

- dpAutoRigSystem/Validator/CheckIn/dpDuplicatedName.py
- dpAutoRigSystem/dpAutoRig.py
Improved the check-in validator DuplicatedName to start the process only if there is any "|" character in the name. So, it's quickly to get result before run the check for all items in the scene.
> N643 DuplicatedName optimize searching

- dpAutoRigSystem/Modules/dpNose.py
- dpAutoRigSystem/dpAutoRig.py
Conform side naming convention to avoid controller mirror shape issue.
> N640 Nose side control renaming

- dpAutoRigSystem/Pipeline/dpPackager.py
- dpAutoRigSystem/dpAutoRig.py
Set the perspective modelEditor to use good default setting when saving the published file.
> N642 reviewed viewport options to publish

- dpAutoRigSystem/dpAutoRig.py
Fixed log when checking all validators.
> N671 Validator check all log fix

- dpAutoRigSystem/Pipeline/dpPublisher.py
- dpAutoRigSystem/dpAutoRig.py
Logging the toClientPath info as exported path.
> N645 - Log image path

- dpAutoRigSystem/Validator/CheckOut/dpHideDataGrp.py
- dpAutoRigSystem/dpAutoRig.py
> N655 HideDataGrp code optimization.

- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/dpAutoRig.py
Fixed running calibration setup just for translation attributes of corrective joints.
> N628 Jcr scaled guides calibration fix.

- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/Extras/dpHeadDeformer.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/Modules/dpFkLine.py
- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/Modules/dpHead.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Modules/dpNose.py
- dpAutoRigSystem/Modules/dpSingle.py
- dpAutoRigSystem/Modules/dpSpine.py
- dpAutoRigSystem/Modules/dpSteering.py
- dpAutoRigSystem/Modules/dpSuspension.py
- dpAutoRigSystem/Modules/dpWheel.py
- dpAutoRigSystem/dpAutoRig.py
Only display rotateOrder attribute in the channelBox of a controller if there are rotates attibutes to animator work.
> N654 Display rotateOrder only if rotate

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Validator/CheckOut/dpResetPose.py
- dpAutoRigSystem/dpAutoRig.py
Fixed the Maya limitation issue about to set the boolean defaultValues.
> N667 set default values bool fix

- dpAutoRigSystem/Extras/dpCustomAttr.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/Modules/dpFkLine.py
- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Modules/dpSingle.py
- dpAutoRigSystem/Modules/dpSteering.py
- dpAutoRigSystem/Modules/dpSuspension.py
- dpAutoRigSystem/Modules/dpWheel.py
- dpAutoRigSystem/Validator/CheckOut/dpResetPose.py
- dpAutoRigSystem/dpAutoRig.py
Changed all possible boolean attributes to integer to avoid conflict with Maya's edit defaultValue limitation.
> N668 Attributes boolean to integer

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/dpAutoRig.py
Added a new guide to Eye module to define the positions and rotation of eyelids base joint. It's useful to oval eyes.
> N680 Center eyelids pivot guide

- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/dpAutoRig.py
Just arranged the position of mirrored JEnd of the Eye module. Thanks to Magdiel for the feedback.
> N478 Eye JEnd position fixed

- dpAutoRigSystem/Extras/dpRivet.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/dpAutoRig.py
Thank you Danilo for the adjustments. 
Pull Requested with the new feature to create a faceToRivet geometry on the dpRivet version 1.6
> 156 faces to rivet

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Pipeline/dpPackager.py
- dpAutoRigSystem/Pipeline/dpPublisher.py
- dpAutoRigSystem/dpAutoRig.py
N702 - Callback conform.
N678 - Open toClient folder after publish.
N677 - Fix ExportLogDicToJson path.
N681 - Copy current wip file to dpHist for backup.
> N702 Callback conform

- dpAutoRigSystem/Controls/dpBaseControlClass.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/dpAutoRig.py
Tagged all controls as Maya's controllers.
> N064 Tag as controller

- dpAutoRigSystem/Controls/dpBaseControlClass.py
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/dpAutoRig.py
Implemented dpID for all controllers.
> N644 controllers dpID

- dpAutoRigSystem/Validator/CheckOut/dpHideCorrectives.py
- dpAutoRigSystem/dpAutoRig.py
Added zero command to zero attribute.
> Added command to zero attribute

- dpAutoRigSystem/dpAutoRig.py
Fixed error with reloading modulesToBeRiggedList before check for imported guides.
> N701 Rigging old rigged module issue fix

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Improved Limb and Foot ankle correctives to work well integrated.
> N639 ankle jcr ball ctrl

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Creating pullRequest after testing branchativa. Last fix adjusted interpolation type from orientConstraint.
> 714 shoulder sub ctrl

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/dpAutoRig.py
Changed dpUtils articulation joint creation orient constraint using shortest now to avoid issue.
> N726 Jar constraint issue fix

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Limb poleVector scale issue.
> N625 Limb poleVector scalable

- dpAutoRigSystem/Modules/dpWheel.py
- dpAutoRigSystem/dpAutoRig.py
> N732 Back wheel new control shapes

- dpAutoRigSystem/Controls/Presets/Classic.json
- dpAutoRigSystem/Controls/Presets/Cubic.json
- dpAutoRigSystem/Controls/Presets/Default.json
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/dpFkLine.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/dpAutoRig.py
Implemented a new FkLine feature to have main controllers. Also we can control the rotate intensity and sub controllers display.
> N734 FkLine main and sub controls

- dpAutoRigSystem/Extras/dpUpdateGuides.py
- dpAutoRigSystem/dpAutoRig.py
Bug fixed: Some guides that did not need update were not being parented to the new guide's created properly, also added scroll layout to summary ui.
> 727-ug-children-fix

- dpAutoRigSystem/Validator/CheckOut/dpUnusedSkinCleaner.py
- dpAutoRigSystem/dpAutoRig.py
Not using OptimizeSceneSize anymore because it removed all optionVariations for user preferences. Just coded a proper algorithm to do the job sweetly.
> N740 Refactoring UnusedSkinCleaner validator

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpBaseClass.py
- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/Modules/dpFkLine.py
- dpAutoRigSystem/dpAutoRig.py
Added a new ik first controller to have the same behavior as last ik control.
Fixed volume variation issue when scaling the rig.
Added fk sub controllers.
> N720 Chain ik first and fk main ctrls

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Changed a parentConstraint to attempt make wider the range of the wrist max rotation before ribbon flipping in the Limb module.
> N733 Limb wrist max rotate flipping

- dpAutoRigSystem/dpAutoRig.py
Fixed Limb ankle flipping issue when rotating Root_Ctrl. Just changed Jax orientConstraint interpolationType to shortest.
> N753 Limb ankle flip fix

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed cine Limb extrem constraints to avoid flipping and wrong interpolation types.
> N754 Limb constraint fixes

- dpAutoRigSystem/Validator/CheckOut/dpSideCalibration.py
- dpAutoRigSystem/dpAutoRig.py
Just avoid error about non existing attributes listed to calibrate. Reports the issue but don't crash anymore when publishing a file.
> N751 SideCalibration fix non existing attribute

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/Modules/dpFkLine.py
- dpAutoRigSystem/Modules/dpLayoutClass.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/Modules/dpSpine.py
- dpAutoRigSystem/dpAutoRig.py
Created a new feature to Chain module to be able to use dynamics.
There're simulation nodes stored in the FX_Grp and new attribute to use traditional animation controllers or the simulation setup.
Also reviewed some attribute naming convention starting with lower case.
> N384 Dynamic Chain

- dpAutoRigSystem/Validator/CheckOut/dpDisplayLayers.py
- dpAutoRigSystem/dpAutoRig.py
Fixed issue without any mesh inside Render_Grp.
Now listing these groups:
["Mesh_Grp", "mesh_grp", "Geo_Grp", "geo_grp", "grp_cache"]
> N765 DisplayLayer renamed or empty fix

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Limb elbow/knee scalable and wrist/ankle subCtrl with unlocked translation.
> N762 jar scalecompensate off, N763 Limb extrem subCtrl translate

- dpAutoRigSystem/Extras/dpCorrectionManager.py
- dpAutoRigSystem/dpAutoRig.py
Calling dpRivet without faceToRivet correctly.
Changed condition nodes to a single choice node to extract angle.
> N759 CorrectionManager call rivet and choise fixes

- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/dpAutoRig.py
Added follow attribute to FootBall control to space switch to Middle control space.
> 547 ball follow middle foot

- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/dpAutoRig.py
Fixed reverseFoot ball controller follow issue.
Also changed Foot ball controller shape.
> N775 ReverseFoot follow issue fix

- dpAutoRigSystem/Validator/CheckOut/dpProxyCreator.py
- dpAutoRigSystem/dpAutoRig.py
Optimized the code to run almost 10 times faster using dictionary instead of looping all joints and vertices for each mesh.
> N778 ProxyCreator fast code

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/dpAutoRig.py
Avoiding tweakers holderMain parenting issue.
> N780 originedFrom fix

- dpAutoRigSystem/Validator/CheckOut/dpBrokenNetCleaner.py
- dpAutoRigSystem/dpAutoRig.py
Added a new function to clean up the IkFkSnap network node.
> Clean-up IkFkSnap network node

- dpAutoRigSystem/Modules/Library/dpControls.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/dpAutoRig.py
Fixed the mirror controller shapes when we have deformers and negative scale of the right side controllers.
> N764 MirrorShape HeadDeformer issue

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpChain.py
- dpAutoRigSystem/dpAutoRig.py
Just replacing member method to call it using Utils function.
> N760 call Utils by Chain Dynamic

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpSingle.py
- dpAutoRigSystem/dpAutoRig.py
Fixed parenting issue when removing the originedFrom attribute of Single main controller.
> N782 Single main children parent

- dpAutoRigSystem/dpAutoRig.py
- dpAutoRigSystem/dpProxyCreator.py
Simple fix to checkout validator Proxy creator working well with meshes with just one skinned joint.
> N783 Proxy creator of just one skinned joint

- dpAutoRigSystem/Pipeline/dpPipeliner.py
- dpAutoRigSystem/dpAutoRig.py
Fixed the issue about trying to publish a file in the root folder, like, for example D:/nilouco.ma
> N770 Root folder pipeliner issue fixed

- dpAutoRigSystem/Extras/dpRivet.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Validator/CheckOut/dpBrokenNetCleaner.py
- dpAutoRigSystem/dpAutoRig.py
New branch to bring rivet remove features.
> 685-rivet-remove new branch

- dpAutoRigSystem/Extras/dpFacialControl.py
- dpAutoRigSystem/dpAutoRig.py
Fix additional flag on control creation, added True for addTranslate, and True for limitMinY. Also completed other flags with False.
> N798-fix-sneer-grimace-translate-y

- dpAutoRigSystem/Validator/CheckOut/dpProxyCreator.py
Updated proxyCreator version to 1.3.
> 799 add fullpath proxy creator

- dpAutoRigSystem/dpAutoRig.py
> N799-add-fullpath-proxy-creator

- dpAutoRigSystem/Extras/dpRivet.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/dpAutoRig.py
Added a user prompt to avoid automatic exclusion of geometries used to hold rivets and added lock to groups to avoid auto exclusion also.
> 801-rivet-prompt

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added a new Limb feature to elbow autoRotate.
> N809 Limb Elbow AutoRotate

- dpAutoRigSystem/Modules/dpFinger.py
- dpAutoRigSystem/dpAutoRig.py
Fixed finger module to avoid double transformation when the finger has the same prefix.
> Fixed finger module build.

- dpAutoRigSystem/Modules/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Fixed isolate attribute and default value when is Arm module.
> 816 fix limb isolate

- dpAutoRigSystem/Validator/CheckOut/dpProxyCreator.py
- dpAutoRigSystem/dpAutoRig.py
Just a clean up of user defined attributes on proxies to avoid have the same custom ID from original meshes.
> N820 Remove userDef attr proxy

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/Library/dpIkFkSnap.py
- dpAutoRigSystem/dpAutoRig.py
Show a window with a download button of the latest version if find an issue.
I hope it'll help to reinstall the dpAutoRigSystem from scratch.
> 808 reinstaller advisor

- dpAutoRigSystem/Deforms/dpSkinning.py
- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/dpAutoRig.py
Fixed the error when trying to add or remove a joint influence to/from a skinCluster if the joint is already connected as influence when adding, or not in the influence list if to remove it.
> N819 Add skin influence

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Modules/dpSpine.py
- dpAutoRigSystem/dpAutoRig.py
Added Option_Ctrl attributes to toggle Spine base and tip controllers shape visibility.
> N833 Spine Controllers display

- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/Modules/dpEye.py
- dpAutoRigSystem/dpAutoRig.py
Right EyeSpecularScale control gets the same rotation and relative position as the left side.
> N814 Eye specular mirror fix

- dpAutoRigSystem/Extras/dpCorrectionManager.py
- dpAutoRigSystem/dpAutoRig.py
Added an UI filter for the CorrectionManager name.
> N832 Correction manager name filter

- dpAutoRigSystem/Extras/dpLimbSpaceSwitch.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Added tail base, ear base, and main controllers, and also added quadruped ik spaceSwitch.
> N829 Quadruped tail, ear, limb spaceSwitch

- dpAutoRigSystem/Modules/dpFoot.py
- dpAutoRigSystem/Scripts/dpBiped.py
- dpAutoRigSystem/Scripts/dpLeg.py
- dpAutoRigSystem/Scripts/dpQuadruped.py
- dpAutoRigSystem/dpAutoRig.py
Added a new reverseFoot pivot to the bottom of the middle controller.
> N849 Middle reverseFoot

- dpAutoRigSystem/Extras/dpUpdateGuides.py
- dpAutoRigSystem/Modules/Library/dpIkFkSnap.py
- dpAutoRigSystem/dpAutoRig.py
Adjusting ik/fk snap from positioned fk was not working. Also added a fix for the new reverse foot guide not updating correctly from older versions.
> 862 ikfksnap state fix

- dpAutoRigSystem/dpAutoRig.py
Just added a message to latest dpAutoRigSystem version 4 to inform user the need of download and install the version 5 manually.
> N878 Latest version 4 update conform

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/dpAutoRig.py
Fixed segmentCompensate for the Limb aditional joints.
> N830 - Limb Jad segmentCompensate off

- dpAutoRigSystem/Modules/Library/dpSkinning.py
- dpAutoRigSystem/dpAutoRig.py
Changed to avoid 1 only skinned joint translation issue.
> N898 - SkinCluster space relative mode to local

- dpAutoRigSystem/Modules/Standard/dpLimb.py
- dpAutoRigSystem/dpAutoRig.py
Added calibration attributes to Limb poleVector controller to adjust the controller offset using the parentConstraint rest translation values.
> N856 - Limb poleVector offset controller

- dpAutoRigSystem/Modules/Standard/dpEye.py
- dpAutoRigSystem/dpAutoRig.py
Added Eye attributes to calibrate fk controller offset.
> N825 - Eye offset control calibration attributes

- dpAutoRigSystem/Modules/Base/dpBaseLayout.py
- dpAutoRigSystem/dpAutoRig.py
Just unlocking transform attributes to be possible mirror pinned guides.
> N253 Mirror pinned guide issue fix

- dpAutoRigSystem/Modules/Standard/dpChain.py
- dpAutoRigSystem/dpAutoRig.py
Fixed Chain module scale by connecting missing attributes to ik joints.
> N896 - Chain scale fix

- dpAutoRigSystem/Modules/Standard/dpChain.py
- dpAutoRigSystem/dpAutoRig.py
Check if there's an Option_Ctrl to connect scalable and avoid issue.
> N913 - Scalable Chain issue fix

- dpAutoRigSystem/Modules/Standard/dpSingle.py
- dpAutoRigSystem/dpAutoRig.py
Avoiding negative scale to tweakers and using a multiplyDivide to calculete the inverse translate values.
> N905 - Maya 2026 conform negative scale issue

- dpAutoRigSystem/Modules/Library/jcRibbon.py
- dpAutoRigSystem/Pipeline/Validator/CheckOut/dpJointEndCleaner.py
- dpAutoRigSystem/dpAutoRig.py
Removed end joint of drive ribbon setup to avoid break the rig. Also added a new conditional to don't remove jointEnds if they have children.
> N915 - JointEndCleaner ribbon issue fix

- dpAutoRigSystem/Pipeline/Validator/CheckOut/dpPruneSkinWeights.py
- dpAutoRigSystem/dpAutoRig.py
Ajusted pruneMinValue to 0.0005
> N919 - Wip Ajusted pruneMinValue to 0.0005

- dpAutoRigSystem/Languages/English.json
- dpAutoRigSystem/Languages/Francais.json
- dpAutoRigSystem/Languages/Portugues.json
- dpAutoRigSystem/Tools/dpReorderAttr.py
- dpAutoRigSystem/dpAutoRig.py
Optimized the ReorderAttr to just pass from hidden attributes.
> N391 - ReorderAttr avoid hidden attributes

- dpAutoRigSystem/Modules/Base/dpBaseStandard.py
- dpAutoRigSystem/Modules/Standard/dpHead.py
- dpAutoRigSystem/Modules/Standard/dpSingle.py
- dpAutoRigSystem/dpAutoRig.py
Adjusted Single Main indirect skinning drive tweakers.
Also fixed Head right lip corner joint parenting and optionCtrl existing instance bug.
> N922 - Single main hook fix

- dpAutoRigSystem/Pipeline/Validator/CheckOut/dpTweakNodeCleaner.py
- dpAutoRigSystem/dpAutoRig.py
Added a conditional to check if we can delete or not the tweak node. We check if there are edited plist.controlPoints to avoid delete it.
> N926 - TweakNodeCleaner controlShape fix

- dpAutoRigSystem/Pipeline/Rebuilder/Source/dpShaderIO.py
- dpAutoRigSystem/dpAutoRig.py
Implemented the Maya2026 openPBRshader conform.
Added an exception to ShaderIO because the attributes "subsurfaceRadius" and "subsurfaceRadiusScale" changed types (float/vector).
> N923 - Maya2026 conform openPBR shader

- dpAutoRigSystem/Pipeline/Validator/CheckIn/dpOneVertex.py
- dpAutoRigSystem/dpAutoRig.py
Changed algorithm from OpenMaya to MEL evaluation to get performance and good results searching for vertex in the nonManifold command return.
> N925 - OneVertex performance fix

- dpAutoRigSystem/Pipeline/dpPackager.py
- dpAutoRigSystem/dpAutoRig.py
Using the right layout panel without remember window size to get the rigging image preview properly.
> N891 - Imager size adjustment

- dpAutoRigSystem/Modules/Base/dpBaseLayout.py
- dpAutoRigSystem/Modules/Integrated/dpBiped.py
- dpAutoRigSystem/Modules/Integrated/dpQuadruped.py
- dpAutoRigSystem/Modules/Library/dpUtils.py
- dpAutoRigSystem/dpAutoRig.py
Fixed the guides mirror in the viewport preview.
> N933 - Mirror guide disappearing fix

- dpAutoRigSystem/Pipeline/Validator/CheckOut/_dpOrderListCheckOut.txt
- dpAutoRigSystem/dpAutoRig.py
Adjusted checkout validator modules order.
> N948 - Clean empty groups before bindPose
